### ISSUE TITLE
Make these styles a class

### ISSUE THREAD

**Issue by john-terenzio** [timothyb9526/TimothyBowlingwebrentalagency#4]
https://github.com/timothyb9526/TimothyBowlingwebrentalagency/blob/a24d7cae5d76d701bdbeeaa8af8353c68da619ff/javascript.js#L27-L29

Instead of adding and removing styles directly in JS you should define a class in your css file that has these styles and then add/remove the class in JS. Example:
```css
.special-class {
  font-size: 5rem;
  color: black;
  font-weight: bolder;
}
```
```js
message.classList.add('special-class');
```
